# Generated by Django 4.0.6 on 2022-07-31 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='corona_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('COUNTRY_NAME', models.CharField(max_length=30)),
                ('ALL_CONFIRMED_CASES', models.IntegerField()),
                ('DEAD_PERSON', models.IntegerField()),
                ('FATALITY_RATE', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='COUNTRY',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('COUNTRY_NAME', models.CharField(max_length=150, unique=True)),
                ('KEYWORD_COUNT', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='naver_news',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NEWS_TITLE', models.CharField(max_length=150)),
                ('NEWS_URL', models.URLField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='trip_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TRAVEL_WARNING', models.CharField(max_length=300)),
                ('QUARANTINE', models.CharField(max_length=300)),
                ('VACCINE', models.CharField(max_length=300)),
                ('CORONA_TEST', models.CharField(max_length=300)),
                ('DOCUMENT_VISA', models.CharField(max_length=300)),
                ('TRAVEL_INSURANCE', models.CharField(max_length=300)),
                ('MASK', models.CharField(max_length=300)),
                ('COUNTRY_NAME', models.CharField(max_length=30)),
            ],
        ),
    ]
