# Generated by Django 4.0.6 on 2022-07-31 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notice_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NOTICE_TITLE', models.CharField(max_length=200, verbose_name='제목')),
                ('NOTICE_WRITER', models.CharField(max_length=30, verbose_name='작성자')),
                ('NOTICE_DATE', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('READCOUNT', models.IntegerField(default=0, verbose_name='조회수')),
                ('NOTICE_CONTENT', models.TextField(null=True, verbose_name='공지내용')),
            ],
        ),
    ]
